### ISSUE TITLE
Add Discussions menu item to this project ?

### ISSUE THREAD

**Issue by sshearer** [Jowan-Spooner/visual-novel-template#1]
Hi :)  I've reviewed some of the files here but don't see anything recognizable yet - are your changes buried in the internals of dialogic or are they yet to be added ?

FYI, I find this topic interesting as I think it is similar to what I'm trying to (slowly) deliver - in my case a 'video' that just plays, but I can see how it could be enhanced later to be interactive and more engaging.

Thanks,
Steven.

**Comment by Jowan-Spooner** [comment]
huh, this is just an old thing. If you are looking for the visual-novel template, then use this one https://github.com/Dialogic-Godot/visual-novel-template.
